# This is a basic workflow to help you get started with Actions

name: Test, Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install deps with yarn    
    - name: Install dependecies
      run: yarn
      working-directory: ./user-service  

    # Run linter checks  
    - name: Run TS lint
      run: yarn lint
      working-directory: ./user-service

    # Run test  
    - name: Run tests
      run: yarn test
      working-directory: ./user-service    

  deploy:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    # only run if build job complete successfully
    needs: [tests]    

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}    
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: 
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build ./user-service --file ./user-service/Dockerfile --tag valeriydockerid/img-user-service:latest

      - name: Docker Push
        run: docker push valeriydockerid/img-user-service  
